version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: models

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 3000:5000
    environment:
      MONGODB_URL: mongo
    depends_on:
      - mongo

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 3001:5000
    environment:
      SERVER_URL: mongo
    restart: on-failure
    depends_on:
      - server
